apiVersion: apps/v1
kind: Deployment
metadata:
  name: clipboard-webapp-deployment
  labels:
    app: clipboard-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clipboard-webapp
  template:
    metadata:
      labels:
        app: clipboard-webapp
    spec:
      containers:
        - name: clipboard-webapp
          image: negan/clipboard-webapp:latest
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: "200m"
              memory: 256Mi
              
          # env vars
          env:
            # secrets
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: clipboard-secrets
                  key: mongo-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clipboard-secrets
                  key: mongo-password

            # config maps
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: clipboard-external-config
                  key: mongo-url
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: clipboard-external-config
                  key: mongo-db-name
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: clipboard-external-config
                  key: mongo-collection-name
            - name: BACKEND_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: clipboard-external-config
                  key: backend-route
            - name: BACKEND_PORT
              value: "3000"
          
          # container port
          ports:
          - containerPort: 3000    
---
apiVersion: v1
kind: Service
metadata:
  name: clipboard-webapp-service
spec:
  type: NodePort
  selector:
    app: clipboard-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
